name: design_system
description: "Design system, containing shared widgets and theming"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.10.0


dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  delayed_display: ^2.0.0
  go_router: ^17.1.0
  shimmer: ^3.0.0
  shimmer_animation: ^2.2.2+1

dev_dependencies:
  build_runner: ^2.11.1
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/graphics/
    - assets/icons/
    - assets/video/
    - assets/fonts/
    - assets/gifs/

  fonts:
    - family: YesevaOne
      fonts:
        - asset: assets/fonts/YesevaOne-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf

flutter_gen:
  output: lib/gen/
  assets:
    outputs:
      package_parameter_enabled: true